// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nam.Server.Data;

#nullable disable

namespace nam.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nam.Server.Models.Entities.Auth.PasswordResetCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResetPasswordAuth");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.Auth.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureCard", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("DetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EntityId");

                    b.HasIndex("DetailIdentifier");

                    b.ToTable("ArtCultureNatureCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.PrimitiveCollection<string>("Gallery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("MunicipalityDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NearestCarParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PrimaryImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectDiscipline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.PrimitiveCollection<string>("VirtualTours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Identifier");

                    b.HasIndex("MunicipalityDataId");

                    b.HasIndex("NearestCarParkId");

                    b.HasIndex("SiteId");

                    b.ToTable("ArtCultureNatureDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.AssociatedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("AssociatedServices");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Catalogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CreativeWorkMobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("CreativeWorkMobiles");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("CulturalProjects");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalSiteService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("CulturalSiteServices");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.FeatureCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("FeatureCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.MobileCategoryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MobileCategoryDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MunicipalityForLocalStorageSetting");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.NearestCarPark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("NearestCarParks");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.SiteCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SiteCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailIdentifier");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", "MunicipalityData")
                        .WithMany()
                        .HasForeignKey("MunicipalityDataId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.NearestCarPark", "NearestCarPark")
                        .WithMany()
                        .HasForeignKey("NearestCarParkId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.SiteCard", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("MunicipalityData");

                    b.Navigation("NearestCarPark");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.AssociatedService", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("AssociatedServices")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Catalogue", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("Catalogues")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CreativeWorkMobile", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("CreativeWorks")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalProject", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("CulturalProjects")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalSiteService", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("Services")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.FeatureCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("Neighbors")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", b =>
                {
                    b.Navigation("AssociatedServices");

                    b.Navigation("Catalogues");

                    b.Navigation("CreativeWorks");

                    b.Navigation("CulturalProjects");

                    b.Navigation("Neighbors");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
