// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nam.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209225710_AddOrganizationEntity")]
    partial class AddOrganizationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nam.Server.Models.Entities.Auth.PasswordResetCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResetPasswordAuth");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.Auth.RevokedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureCard", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("DetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EntityId");

                    b.HasIndex("DetailIdentifier");

                    b.ToTable("ArtCultureNatureCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.PrimitiveCollection<string>("Gallery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("MunicipalityDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NearestCarParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PrimaryImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectDiscipline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.PrimitiveCollection<string>("VirtualTours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Identifier");

                    b.HasIndex("MunicipalityDataId");

                    b.HasIndex("NearestCarParkId");

                    b.HasIndex("SiteId");

                    b.ToTable("ArtCultureNatureDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArticleCard", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EntityId");

                    b.HasIndex("DetailIdentifier");

                    b.ToTable("ArticleCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArticleDetail", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("MunicipalityDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.PrimitiveCollection<string>("Themes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeToRead")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Identifier");

                    b.HasIndex("MunicipalityDataId");

                    b.ToTable("ArticleDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.AssociatedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("AssociatedServices");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Catalogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CreativeWorkMobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("CreativeWorkMobiles");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("CulturalProjects");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalSiteService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.ToTable("CulturalSiteServices");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.FeatureCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtCultureNatureDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrganizationMobileDetailTaxCode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PublicEventMobileDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArtCultureNatureDetailIdentifier");

                    b.HasIndex("OrganizationMobileDetailTaxCode");

                    b.HasIndex("PublicEventMobileDetailIdentifier");

                    b.ToTable("FeatureCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.MobileCategoryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MobileCategoryDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MunicipalityForLocalStorageSettings");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Nature", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("DetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EntityId");

                    b.HasIndex("DetailIdentifier");

                    b.ToTable("Natures");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.NearestCarPark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("NearestCarParks");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationMobileDetailTaxCode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PriceSpecificationCurrencyValue")
                        .HasColumnType("float");

                    b.Property<Guid?>("PublicEventMobileDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TicketDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidityEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidityStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationMobileDetailTaxCode");

                    b.HasIndex("PublicEventMobileDetailIdentifier");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OrganizationCard", b =>
                {
                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BadgeText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailTaxCode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("TaxCode");

                    b.HasIndex("DetailTaxCode");

                    b.ToTable("OrganizationCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", b =>
                {
                    b.Property<string>("TaxCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Gallery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LegalName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LegalStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("MainFunction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("MunicipalityDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NearestCarParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Website")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("TaxCode");

                    b.HasIndex("MunicipalityDataId");

                    b.HasIndex("NearestCarParkId");

                    b.ToTable("OrganizationMobileDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OwnedPoi", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OfficialName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrganizationMobileDetailTaxCode")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identifier");

                    b.HasIndex("OrganizationMobileDetailTaxCode");

                    b.ToTable("OwnedPois");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Paragraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleDetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("ReferenceLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("ReferenceLongitude")
                        .HasColumnType("float");

                    b.Property<string>("ReferenceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleDetailIdentifier");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.PublicEventCard", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("DetailIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("MunicipalityDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrganizationMobileDetailTaxCode")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EntityId");

                    b.HasIndex("DetailIdentifier");

                    b.HasIndex("MunicipalityDataId");

                    b.HasIndex("OrganizationMobileDetailTaxCode");

                    b.ToTable("PublicEventCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.PublicEventMobileDetail", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Gallery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("MunicipalityDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NearestCarParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typology")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("VirtualTours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identifier");

                    b.HasIndex("MunicipalityDataId");

                    b.HasIndex("NearestCarParkId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("PublicEventMobileDetails");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.SiteCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SiteCards");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailIdentifier");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", "MunicipalityData")
                        .WithMany()
                        .HasForeignKey("MunicipalityDataId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.NearestCarPark", "NearestCarPark")
                        .WithMany()
                        .HasForeignKey("NearestCarParkId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.SiteCard", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("MunicipalityData");

                    b.Navigation("NearestCarPark");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArticleCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArticleDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailIdentifier");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArticleDetail", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", "MunicipalityData")
                        .WithMany()
                        .HasForeignKey("MunicipalityDataId");

                    b.Navigation("MunicipalityData");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.AssociatedService", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("AssociatedServices")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Catalogue", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("Catalogues")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CreativeWorkMobile", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("CreativeWorks")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalProject", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("CulturalProjects")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.CulturalSiteService", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("Services")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.FeatureCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", null)
                        .WithMany("Neighbors")
                        .HasForeignKey("ArtCultureNatureDetailIdentifier");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", null)
                        .WithMany("Neighbors")
                        .HasForeignKey("OrganizationMobileDetailTaxCode");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.PublicEventMobileDetail", null)
                        .WithMany("Neighbors")
                        .HasForeignKey("PublicEventMobileDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Nature", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailIdentifier");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Offer", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", null)
                        .WithMany("Offers")
                        .HasForeignKey("OrganizationMobileDetailTaxCode");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.PublicEventMobileDetail", "PublicEventMobileDetail")
                        .WithMany("TicketsAndCosts")
                        .HasForeignKey("PublicEventMobileDetailIdentifier");

                    b.Navigation("PublicEventMobileDetail");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OrganizationCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailTaxCode");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", "MunicipalityData")
                        .WithMany()
                        .HasForeignKey("MunicipalityDataId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.NearestCarPark", "NearestCarPark")
                        .WithMany()
                        .HasForeignKey("NearestCarParkId");

                    b.Navigation("MunicipalityData");

                    b.Navigation("NearestCarPark");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OwnedPoi", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", null)
                        .WithMany("OwnedPoi")
                        .HasForeignKey("OrganizationMobileDetailTaxCode");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.Paragraph", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.ArticleDetail", null)
                        .WithMany("Paragraphs")
                        .HasForeignKey("ArticleDetailIdentifier");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.PublicEventCard", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.PublicEventMobileDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailIdentifier");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", "MunicipalityData")
                        .WithMany()
                        .HasForeignKey("MunicipalityDataId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", null)
                        .WithMany("Events")
                        .HasForeignKey("OrganizationMobileDetailTaxCode");

                    b.Navigation("Detail");

                    b.Navigation("MunicipalityData");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.PublicEventMobileDetail", b =>
                {
                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.MunicipalityForLocalStorageSetting", "MunicipalityData")
                        .WithMany()
                        .HasForeignKey("MunicipalityDataId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.NearestCarPark", "NearestCarPark")
                        .WithMany()
                        .HasForeignKey("NearestCarParkId");

                    b.HasOne("nam.Server.Models.Entities.MunicipalityEntities.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId");

                    b.Navigation("MunicipalityData");

                    b.Navigation("NearestCarPark");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArtCultureNatureDetail", b =>
                {
                    b.Navigation("AssociatedServices");

                    b.Navigation("Catalogues");

                    b.Navigation("CreativeWorks");

                    b.Navigation("CulturalProjects");

                    b.Navigation("Neighbors");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.ArticleDetail", b =>
                {
                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.OrganizationMobileDetail", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Neighbors");

                    b.Navigation("Offers");

                    b.Navigation("OwnedPoi");
                });

            modelBuilder.Entity("nam.Server.Models.Entities.MunicipalityEntities.PublicEventMobileDetail", b =>
                {
                    b.Navigation("Neighbors");

                    b.Navigation("TicketsAndCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
